from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    message: str = Field(..., description="The message to send to the chat model.", min_length=1, max_length=1000)
    conversation_id: str | None = Field(None, description="The unique identifier for the conversation.")

class ChatResponse(BaseModel):
    message: str = Field(..., description="The response generated by the agent.")
    conversation_id: str  = Field(..., description="The unique identifier for the conversation.")
